name: Your New Jekyll Site
markdown: redcarpet
highlighter: pygments
paginate: 5
paginate_path: "blog/page:num"
permalink: "/:year/:month/:title/"
brandname: TinkerSoc
live: true
menufolders:
 - /blog
dropdowns:
 - Resources

category_dir: "blog"

picture:
  source: assets/images/_fullsize
  output: assets/images/generated
  markup: "picturefill"
  presets:
    face:
      ppi: [1, 1.5]
      attr:
        class: face
      source_default:
        width: 240px
        height: 240px

    default:
      ppi: [1, 1.5]
      attr:
        class: "test"
        itemprop: "image"
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
      source_default: 
        width: "300"
    carousel-narow:
      ppi: [1, 1.5]
      attr:
        class: "col-md-3 col-md-offset-6"
        itemprop: "image"
      source_xs:
        media: "(max-width: 480)"
        width: "240"
      source_sm:
        media: "(min-width: 481px) and (max-width: 768px)"
        width: "384"
      source_default:
        width: "960"
    carousel:
      ppi: [1, 1.5]
      attr:
        class: "img-carousel"
        itemprop: "image"
      source_xs:
        media: "(max-width: 480px)"
        width: "480"
      source_sm:
        media: "(min-width: 481px) and (max-width: 768px)"
        width: "768"
      source_default: 
        width: "1920"
    icon:
      ppi: [1, 1.5]
      attr:
        class: "icon"
        itemprop: "image"
      source_default: 
        height: "32px"

flickr_set:
  gallery_tag:   'div'
  gallery_class: 'gallery'
  gallery_id:    'container'
  a_href:        'b'
  a_target:      '_blank'
  image_rel:     ''
  image_size:    'm'
  image_class:   'item'
  api_key:       '251b6a7131ff48d65978013ff47083d1'

