name: Your New Jekyll Site
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "blog/page:num"
brandname: TinkerSoc
menufolders:
 - /blog
dropdowns:
 - Resources
picture:
  source: assets/images/_fullsize
  output: generated
  markup: "picturefill"
  presets:
    default:
      ppi: [1, 1.5]
      attr:
        class: "test"
        itemprop: "image"
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
      source_default: 
        width: "300"
    carousel:
      ppi: [1, 1.5]
      attr:
        class: "img-carousel"
        itemprop: "image"
      source_medium:
        media: "(min-width: 40em)"
        height: "500"
      source_default: 
        width: "300"
    icon:
      ppi: [1, 1.5]
      attr:
        class: "icon"
        itemprop: "image"
      source_default: 
        width: "32px"

flickr_set:
  gallery_tag:   'div'
  gallery_class: 'gallery'
  gallery_id:    'container'
  a_href:        'b'
  a_target:      '_blank'
  image_rel:     ''
  image_size:    'm'
  image_class:   'item'
  api_key:       '251b6a7131ff48d65978013ff47083d1'

